### ISSUE TITLE
Builds failing: no Go files in /go/src/github.com/jinzhu/gorm

### ISSUE THREAD

**Issue by thejcartwright** [t0mbs/voxper#1]
Docker builds are currently failing with the following error message:
```
github.com/jinzhu/gorm (download)
package github.com/jinzhu/gorm: no Go files in /go/src/github.com/jinzhu/gorm
package github.com/jinzhu/gorm/dialects/postgres: cannot find package "github.com/jinzhu/gorm/dialects/postgres" in any of:
	/usr/local/go/src/github.com/jinzhu/gorm/dialects/postgres (from $GOROOT)
	/go/src/github.com/jinzhu/gorm/dialects/postgres (from $GOPATH)
```

I am looking forward to seeing this project evolve.

**Comment by t0mbs** [comment]
Thanks for flagging this. It seems like the default branch for the jinzhu GORM project was switched from `master` to `v2`. The later does not contain any Go code, and this seems to be some kind of mistake by the repo owner. Go pulls the default branch in the context of its dependency management. As a result `RUN go get -d -v ./...` on l.17 of the Dockerfile pulls v2 of the jinzhu GORM repo, which causes the error.

To temporarily resolve this issue I forked the GORM repository, set its default branch to `master` and updated the references in code.

You can find this hotfixed here: https://github.com/t0mbs/voxper/tree/v0.1.1

**Comment by t0mbs** [comment]
Thanks for flagging this. It seems like the default branch for the jinzhu GORM project was switched from `master` to `v2`. The later does not contain any Go code, and this seems to be some kind of mistake by the repo owner. Go pulls the default branch in the context of its dependency management. As a result `RUN go get -d -v ./...` on l.17 of the Dockerfile pulls v2 of the jinzhu GORM repo, which causes the error.

To temporarily resolve this issue I forked the GORM repository, set its default branch to `master` and updated the references in code.

You can find this hotfixed here: https://github.com/t0mbs/voxper/tree/v0.1.1
